generator:
  class: sfDoctrineGenerator
  param:
    model_class:           aPollPoll
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          a_poll_poll_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions
    i18n_catalogue:        apostrophe

    config:
      actions: ~
      fields: 
        published_from: 
          label: Published from
        published_to: 
          label: Published to
      list:    
        title:   Polls administration
        display: [=name, description, type, published_from, published_to]
      filter:  
        display: [name, type, published_from, published_to]
      form:    ~
      edit:    ~
      new:     
        title: New Poll
