generator:
  class: sfDoctrineGenerator
  param:
    model_class:           aPollPoll
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          a_poll_poll_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions
    i18n_catalogue:        apostrophe

    config:
      actions: ~
      
      fields: 
        type:
          label: Template
          help: Select the type of poll you want to publish. They are defined in app.yml
        published_from: 
          label: Published from
          help: Leave this value blank, if you don't want to limit publication start.
        published_to: 
          label: Published to
          help: Leave this value blank, if you don't want to limit publication end.
        submissions_allow_multiple:
          label: Allow multiple submissions?
          help: Can a user submit multiple answers, one after the other?
        submissions_delay:
          label: Submissions delay (hh:mm)
          help: How much time must wait a user willing to submit a new answer? This setting only applies if if consecutive submissions are not allowed.          
        nb_answers:
          label: Answers count
          
      list:    
        title:   Polls administration
        display: [=id, title, type, nb_answers, published_from, published_to, created_at ]
        object_actions:
          _edit:         ~
          _delete:       ~
          listAnswers:   { label: List answers, action: listAnswers }
          exportAnswers: { label: Export answers, action exportAnswers }
      filter:  
        display: [type, published_from, published_to]
        
      form:    ~
      
      edit:    
        title: Edit Poll
        actions:
          _save_and_list: ~
          _list:         ~
          _delete:       ~
          previewPoll:   { label: Preview poll, action: previewPoll }
        display:
          General: [type, published_from, published_to, submissions_allow_multiple, submissions_delay]
          Translations: [<?php echo implode(', ',sfConfig::get('app_a_i18n_languages')) ?>]
          
      new:     
        title: New Poll
        actions:
          _save_and_list: ~
          _list:         ~
          _delete:       ~
          previewPoll:   { label: Preview poll, action: previewPoll }
        display:
          General: [type, published_from, published_to, submissions_allow_multiple, submissions_delay]
          Translations: [<?php echo implode(', ',sfConfig::get('app_a_i18n_languages')) ?>]
