<?php

/**
 * PluginaPollSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    apostrophePollPlugin
 * @subpackage ##SUBPACKAGE##
 * @author     Raffaele Bolliger <raffaele.bolliger at gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginaPollSlot extends BaseaPollSlot
{
    protected $editDefault = true;

}