<?php

/**
 * PluginaPollAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPollAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPollAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPollAnswer');
    }
    
    
    public function getByIdWithFieldsAndPoll($params) {
        
        
        $q = $this->getInstance()->createQuery('a')
                ->addWhere('a.id = ?',$params['id'])
                ->leftJoin('a.Fields f')
                ->leftJoin('a.Poll p');
        
        return $q->execute();
        
    }
}