<?php

/**
 * PluginaPollAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    apostrophePollPlugin
 * @subpackage aPollAnswerAdmin
 * @author     Raffaele Bolliger <raffaele.bolliger at gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginaPollAnswer extends BaseaPollAnswer
{
    
    function getFieldsAsArray() {
        
        $fields = $this->getFields();
        $values = array();
        foreach ($fields as $field) {
            $values = array_merge($values, array($field->getName() => $field->getValue()));
        }
        
        return $values;
        
    }

}