<?php

/**
 * PluginaPollPoll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Raffaele Bolliger <raffaele.bolliger at gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginaPollPoll extends BaseaPollPoll
{
    
    public function __toString() {
        
        return $this->getTitle();
    }
    
    public function getNbAnswers() {
         return $this->getAnswers()->count();
    }

}