<?php

/**
 * PluginaPollPollNewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPollPollNewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPollPollNewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPollPollNew');
    }
}