<?php

/**
 * PluginaPollAnswerFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPollAnswerFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPollAnswerFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPollAnswerField');
    }
}