<?php

/**
 * PluginaPollSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPollSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPollSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPollSlot');
    }
}