generator:
  class: sfDoctrineGenerator
  param:
    model_class:           aPollAnswer
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          a_poll_answer_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions
    i18n_catalogue:        apostrophe

    config:
      actions: ~
      
      fields: 
        remote_address:
          label: Posted from
        culture: 
          label: Submission language
          renderer: [aPollAnswerAdminGeneratorHelper, renderCulture]
        created_at: 
          label: Submission date
        id:
          renderer: [aPollAnswerAdminGeneratorHelper, linkToShow]
        poll_id:
          label: Poll
          
          
      list:    
        title:   Answers administration
        display: [=id, is_new, remote_address, culture, created_at]
        actions:
          backToPolls: { label: Back to Polls, action: backToPolls, params: {id = %%id%%} }
        object_actions:
          _delete: ~
        batch_actions:
          _delete: ~
          setRead:   { label: Set as read, action: setRead }
        sort:           [is_new, desc]
      filter:  
        display: [remote_address, culture, created_at]
        
      form:    
        display: [poll_id, remote_address, culture, created_at]
      
      edit:    ~
    
      new:     ~

