all:
  stylesheets:
    - /apostrophePollPlugin/css/a-poll.less: { data-asset-group: global }

  javascripts:
    - /apostrophePollPlugin/js/aPoll.js: { data-asset-group: global }   
    - /apostrophePollPlugin/js/jquery.ui.datepicker-fr.js: { data-asset-group: global } 